### ISSUE TITLE
Missing maven snapshots

### ISSUE THREAD

**Issue by fommil** [trygvis/javax-usb-libusb1#5]
I'm assuming that there is no maven artefact for this library and the documentation to locally install still stands.

```

javax-usb-libusb1-master:mvn install
[INFO] Scanning for projects...
[WARNING] The POM for org.apache.maven.plugins:maven-nar-plugin:jar:2.1-SNAPSHOT is missing, no dependency information available
Downloading: http://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
Downloaded: http://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar (165 KB at 209.2 KB/sec)
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project no.hackaton.usb:javax-usb-libusb1:1.0.1-1-SNAPSHOT (/Users/samuel/Documents/Projects/emokit/javax-usb-libusb1-master/pom.xml) has 3 errors
[ERROR]     Child module /Users/samuel/Documents/Projects/emokit/javax-usb-libusb1-master/cpptasks-parallel/pom.xml of /Users/samuel/Documents/Projects/emokit/javax-usb-libusb1-master/pom.xml does not exist
[ERROR]     Child module /Users/samuel/Documents/Projects/emokit/javax-usb-libusb1-master/maven-nar-plugin/pom.xml of /Users/samuel/Documents/Projects/emokit/javax-usb-libusb1-master/pom.xml does not exist
[ERROR]     Unresolveable build extension: Plugin org.apache.maven.plugins:maven-nar-plugin:2.1-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.apache.maven.plugins:maven-nar-plugin:jar:2.1-SNAPSHOT -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

**Comment by fommil** [comment]
I should not that I have libusb installed under /opt/local using MacPorts.

**Comment by trygvis** [comment]
Hm, can you try to the nar plugin by itself? It should work, but there's probably something earlier in the logs that's relevant for the error.

libusb from MacPorts probably won't work as they don't include my get_speed patch. This error is not related to that. Yet.

**Comment by fommil** [comment]
@trygvis I don't know what you mean by "try to the nar plugin"?

**Comment by fommil** [comment]
@trygvis btw, I'm having reasonable success accessing libusb 0.1 directly with libusb4j, it offers a very nice "pure java" (in a way) solution to usb access. Once you see how libusb4j (and JNA) works, I'm sure you'd be keen to use that as your way to access libusb in the future.

**Comment by trygvis** [comment]
Go into the maven-nar-plugin directory and try to build that.

I'm not going to use libusb4j/jna, I did not find them to be particulary useful to implement the javax.usb classes (too much C/Java impedance).

**Comment by fommil** [comment]
it's empty

**Comment by fommil** [comment]
does this library deal with HDI on OS X correctly?

See here for an explanation https://github.com/openyou/emokit/issues/54#issuecomment-11721868

**Comment by trygvis** [comment]
Ah, if it's empty it's probably because you haven't run git submodule init/sync/update (I can't ever remember the right combo). Basically you're missing the source code for the nar plugin which is required.

I don't remember the state of libusb+hid on OSX, but it all depends on libusb so check their docs. This library is just a thin wrapper on top of libusb.

**Comment by fommil** [comment]
Aaah, the subtleties of the phrase "To build the main software a mvn install will be sufficient." suddenly become clear ;-)

I've hit a problem with libusb4j when using HID devices on OS X. Basically the OS grabs the HID devices for itself and libusb can't do anything. I've been told this needs kernel calls to bypass. Does your library solve this problem? (presumably you'll hit the same issues).

BTW, if you were to use JNA it would mean that your library could be much more easily distributed and installed. JNI is just impossible to deal with properly in Maven. When I have some JNI code, I tend to hide it away in a corner and not expose any of that detail in my own API. I don't see how JNA in Java is any worse than JNI in C! :-P The only real argument against it is performance, which can only be proved with profiled tests (which I did for BLAS/LAPACK).

Note that libusb4j is using libusb0.1, so I think the JNA stubs would have to be updated for it to be worthwhile. I must admit, I'm really impressed by JNA – I've only used JNI in anger before.

If your library ditched JNI and was able to address the HID problems with libusb, I'd move over in a heartbeat and update all the stackoverflow / forum messages I could find in order to sing your praises!

**Comment by trygvis** [comment]
My library will not use JNA, the JNI code is just fine. It will also continue to be a small wrapper around libusb to implement javax.usb, nothing more. I doubt I will add any special code to support HID devices, if I ever needed it I'd probably make a similar wrapper around libhid or whatever the libusb folks recommend.

**Comment by fommil** [comment]
As you wish.

FYI, this is the project I'm working on and you can see how easy it is to use the hidapi via Maven:

  https://github.com/fommil/emokit/tree/master/java

I would be happier with a JNA approach, but they have very sensibly bundled their JNI and made the whole library available through Maven. So the JNI problem is at least abstracted away from my perspective.

I would rather use JSR-80, because I'm a stickler for standards, but in the absence of an easy install or support for HID, then I'm afraid your library is not for me.
