### ISSUE TITLE
Child module missing - cpptasks-parallel and maven-nar-plugin

### ISSUE THREAD

**Issue by gsanson** [trygvis/javax-usb-libusb1#6]
The last thread on this issue did not lead to a solution so I'm posting this again.
I've downloaded both the cpptasks-parallel and maven-nar-pluging, built them, installed them in my local repository. I can browse the repository and both are there
org.codeswarm:maven-nar-plugin
org.codeswarm:cpptasks-parallel

When I build from inside NetBeans 7 I get the following errors:
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
Child module C:\projects\javax-usb-libusb1-master\cpptasks-parallel\pom.xml of C:\projects\javax-usb-libusb1-master\pom.xml does not exist @ 
Child module C:\projects\javax-usb-libusb1-master\maven-nar-plugin\pom.xml of C:\projects\javax-usb-libusb1-master\pom.xml does not exist @ 

Please help me resolve this - I'm pretty new to Maven and this just baffles me.
Thanks in advance for your help!

Regards,
Gary

**Comment by trygvis** [comment]
Ok, I've tried to improve the build now. I forked and releases the dependencies under my own group id and updated the pom to use that. Please pull and try again.

**Comment by trygvis** [comment]
Btw, it might take a couple of hours to the central repository to become updated, so if it can't download the dependencies please try again later.

**Comment by trygvis** [comment]
Or you can add this as a remote repository: https://oss.sonatype.org/content/repositories/releases/

**Comment by gsanson** [comment]
Thanks very much!
Now the build fails on the libusb.home, etc. env variables. Can you tell me how they should be set?

Regards,
Gary

**Comment by trygvis** [comment]
Try reading the readme.
